### ISSUE TITLE
ESP32-S2  Not working

### ISSUE THREAD

**Issue by absn12** [khoih-prog/ESP32_ISR_Servo#2]
ESP32-S2  Not working

**Comment by khoih-prog** [comment]
The library **doesn't support ESP32-S2** as it's written before the introduction of ESP32-S2.
The timer interrupt for ESP32-S2 is different from that of ESP32 as you can see I had to write a different [**ESP32_S2_TimerInterrupt**](https://github.com/khoih-prog/ESP32_S2_TimerInterrupt).

I'll definitely consider to write a new **ESP32-S2_ISR_Servo** in the near future.

**Comment by khoih-prog** [comment]
Hi @absn12 

The new [**ESP32_S2_ISR_Servo** library](https://github.com/khoih-prog/ESP32_S2_ISR_Servo) has been created and  published.

Please test and report any issue there.

Cheers,

---

### Releases v1.1.0

1. Basic **16 ISR-based servo controllers** using 1 hardware timer for **ESP32_S2**.
2. Tested with **ESP32 core v2.0.0-rc1 and v1.0.6**
