### ISSUE TITLE
ESP32-S2 - Twitching randomly

### ISSUE THREAD

**Issue by c-ridgway** [khoih-prog/ESP32_ISR_Servo#7]
### Describe the bug

Just setting up the pin of a servo is enough to make it twitch. I've tried other pins, this also happens on them.

### Information

Please ensure to specify the following:

Platform.io - Core 6.1.5 Home 3.4.3
ESP32-S2 - WEMOS S2 MINI

### Example

```
#ifndef ESP32
  #error This code is designed to run on ESP32 platform, not Arduino nor ESP8266! Please check your Tools->Board setting.
#endif

#define TIMER_INTERRUPT_DEBUG       1
#define ISR_SERVO_DEBUG             1

// Select different ESP32 timer number (0-3) to avoid conflict
#define USE_ESP32_TIMER_NO          3

// To be included only in main(), .ino with setup() to avoid `Multiple Definitions` Linker Error
#include "ESP32_ISR_Servo.h"

//See file .../hardware/espressif/esp32/variants/(esp32|doitESP32devkitV1)/pins_arduino.h
#if !defined(LED_BUILTIN)
  #define LED_BUILTIN       2         // Pin D2 mapped to pin GPIO2/ADC12 of ESP32, control on-board LED
#endif

#define PIN_LED           2         // Pin D2 mapped to pin GPIO2/ADC12 of ESP32, control on-board LED

#define PIN_D0            0         // Pin D0 mapped to pin GPIO0/BOOT/ADC11/TOUCH1 of ESP32
#define PIN_D1            1         // Pin D1 mapped to pin GPIO1/TX0 of ESP32
#define PIN_D2            2         // Pin D2 mapped to pin GPIO2/ADC12/TOUCH2 of ESP32
#define PIN_D3            3         // Pin D3 mapped to pin GPIO3/RX0 of ESP32
#define PIN_D4            4         // Pin D4 mapped to pin GPIO4/ADC10/TOUCH0 of ESP32
#define PIN_D5            5         // Pin D5 mapped to pin GPIO5/SPISS/VSPI_SS of ESP32
#define PIN_D6            6         // Pin D6 mapped to pin GPIO6/FLASH_SCK of ESP32
#define PIN_D7            7         // Pin D7 mapped to pin GPIO7/FLASH_D0 of ESP32
#define PIN_D8            8         // Pin D8 mapped to pin GPIO8/FLASH_D1 of ESP32
#define PIN_D9            9         // Pin D9 mapped to pin GPIO9/FLASH_D2 of ESP32

// Published values for SG90 servos; adjust if needed
#define MIN_MICROS      800  //544
#define MAX_MICROS      2450

int servoIndex1  = -1;
int servoIndex2  = -1;

void setup()
{
  Serial.begin(115200);
  while (!Serial);

  delay(200);

  Serial.print(F("\nStarting ISR_MultiServos on ")); Serial.println(ARDUINO_BOARD);
  Serial.println(ESP32_ISR_SERVO_VERSION);
  
  //Select ESP32 timer USE_ESP32_TIMER_NO
  ESP32_ISR_Servos.useTimer(USE_ESP32_TIMER_NO);

  servoIndex1 = ESP32_ISR_Servos.setupServo(PIN_D5, MIN_MICROS, MAX_MICROS);
  servoIndex2 = ESP32_ISR_Servos.setupServo(PIN_D6, MIN_MICROS, MAX_MICROS);

  if (servoIndex1 != -1)
    Serial.println(F("Setup Servo1 OK"));
  else
    Serial.println(F("Setup Servo1 failed"));

  if (servoIndex2 != -1)
    Serial.println(F("Setup Servo2 OK"));
  else
    Serial.println(F("Setup Servo2 failed"));
}

```

### Additional context

---

### Sending Feature Requests

Feel free to post feature requests. It's helpful if you can explain exactly why the feature would be useful.

There are usually some outstanding feature requests in the [existing issues list](https://github.com/khoih-prog/ESP32_ISR_Servo/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement), feel free to add comments to them.

---

### Sending Pull Requests

Pull Requests with changes and fixes are also welcome!

Please use the `astyle` to reformat the updated library code as follows (demo for Ubuntu Linux)

1. Change directory to the library GitHub

```
xy@xy-Inspiron-3593:~$ cd Arduino/xy/ESP32_ISR_Servo_GitHub/
xy@xy-Inspiron-3593:~/Arduino/xy/ESP32_ISR_Servo_GitHub$
```

2. Issue astyle command

```
xy@xy-Inspiron-3593:~/Arduino/xy/ESP32_ISR_Servo_GitHub$ bash utils/restyle.sh
```

**Comment by khoih-prog** [comment]
Check [**SERVO - How to eliminate micromotion at startup**?](https://forum.arduino.cc/t/servo-how-to-eliminate-micromotion-at-startup/1061642), especially [**post 7**](https://forum.arduino.cc/t/servo-how-to-eliminate-micromotion-at-startup/1061642/7).

Hopefully it'll help, especially while using cheap (or clone / fake) servo **SG90**.

Also try 

1. [**ESP32Servo**](https://github.com/jkb-git/ESP32Servo) or any of plenty ESP32 Servo libraries
2. [**ServoEasing**](https://github.com/ArminJo/ServoEasing)

 to see if better.

**Comment by Turbine1991** [comment]
> Check [**SERVO - How to eliminate micromotion at startup**?](https://forum.arduino.cc/t/servo-how-to-eliminate-micromotion-at-startup/1061642), especially [**post 7**](https://forum.arduino.cc/t/servo-how-to-eliminate-micromotion-at-startup/1061642/7).
> 
> Hopefully it'll help, especially while using cheap (or clone / fake) servo **SG90**.
> 
> Also try
> 
> 1. [**ESP32Servo**](https://github.com/jkb-git/ESP32Servo) or any of plenty ESP32 Servo libraries
> 2. [**ServoEasing**](https://github.com/ArminJo/ServoEasing)
> 
> to see if better.

I managed to get it working by using the built in functionality to control the servos.
