### ISSUE TITLE
[ESP32-S2] Random twitching/moving or servos

### ISSUE THREAD

**Issue by c-ridgway** [khoih-prog/ESP32_ISR_Servo#8]
### Describe the bug

Just setting up the pin for the servo is enough to make it twitch. I've tried multiple I/O pins, to no avail. It's only budging a minute amount. It has pauses inbetween, but it's irregular in pattern.

I plugged it into my other servo and it just made it move all the way to a position, and then twitch.

### Information

ESP32-S2 - Wemos Mini S2
Platform.io - 6.1.5
ESP32_ISR_Servo - 1.5.0
SG90 Servo

### Example

```
#define TIMER_INTERRUPT_DEBUG       1
#define ISR_SERVO_DEBUG             1
#define USE_ESP32_TIMER_NO          3
#define PIN_D15            15
// Published values for SG90 servos; adjust if needed
#define MIN_MICROS      800  //544
#define MAX_MICROS      2450

#include "ESP32_ISR_Servo.h"

int servoIndex1  = -1;

void setup()
{
  Serial.begin(115200);
  sleep(2);

  ESP32_ISR_Servos.useTimer(USE_ESP32_TIMER_NO);
  servoIndex1 = ESP32_ISR_Servos.setupServo(D15, MIN_MICROS, MAX_MICROS);
}

void loop() {
  delay(30);
}
```

**Comment by khoih-prog** [comment]
Check [**SERVO - How to eliminate micromotion at startup**?](https://forum.arduino.cc/t/servo-how-to-eliminate-micromotion-at-startup/1061642), especially [**post 7**](https://forum.arduino.cc/t/servo-how-to-eliminate-micromotion-at-startup/1061642/7).

Hopefully it'll help, especially while using cheap (or clone / fake) servo **SG90**.

Also try 

1. [**ESP32Servo**](https://github.com/jkb-git/ESP32Servo) or any of plenty ESP32 Servo libraries
2. [**ServoEasing**](https://github.com/ArminJo/ServoEasing)

 to see if better.
